---
name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -sSL https://github.com/reconquest/shdoc/releases/download/v1.1/shdoc > /usr/local/bin/shdoc && chmod +x /usr/local/bin/shdoc
      - run: npm ci --force && npm run build:prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: install-doctor
